name: Analytics
on: push

jobs:
  pester-test:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out repository code
        uses: SecureHats/private@v0.3.0-alpha
