name: Analytics
on: push

jobs:
  pester-test:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate Sentinel Analytics Rules
        uses: SecureHats/private@v0.1.16-beta
        with:
          filesPath: templates
          options: Diagnostic
