name: Analytics
on: push

jobs:
  pester-test:
    name: Validation
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate Sentinel Analytics Rules
        uses: SecureHats/private@v4.2.0-alpha
        with:
          filesPath: templates
